### ISSUE TITLE
 `webpack-dev-server --progress --colors --display-error-details --host=0.0.0.0`

### ISSUE THREAD

**Issue by ito2307** [aepsilon/turing-machine-viz#1]
i run npm i and npm i --no-bin-links but i got this error  `webpack-dev-server --progress --colors --display-error-details --host=0.0.0.0` and also i installed npm i webpack-dev-server

**Comment by aepsilon** [comment]
Closing to clean up. We resolved the problem over email. To summarize:
1. `webpack-dev-server` was missing as a devDependency. Fixed in b20bb7c.
2. `webpack-dev-server` failed to start under Laravel Homestead (not related to this repo). A workaround was to serve pre-built static content or run webpack beforehand.
